In [27]:
import torch

weights = torch.tensor([[1.0, -1.0], [2.0, -2.0], [3.0, -3.0]])
x = torch.tensor([[[1.0, 2.0], [3.0, 2.0]]])

W_expanded = weights.unsqueeze(0).unsqueeze(0)  # Shape (1, 1, out_dim, in_dim)
X_expanded = x.unsqueeze(2)  # Shape (batch_dim, time_dim, 1, in_dim)
print(W_expanded.shape)
print(X_expanded.shape)
Y = W_expanded * X_expanded  # Shape (batch_dim, time_dim, out_dim, in_dim)
print(Y.shape)
print(Y)
print((Y > 2.5).float())
print((Y > 2.5).float().mean(dim=-1).flatten())
print(((Y > 2.5).float().mean(dim=-1).flatten() - 0.5).abs().mean())

torch.Size([1, 1, 3, 2])
torch.Size([1, 2, 1, 2])
torch.Size([1, 2, 3, 2])
tensor([[[[ 1., -2.],
          [ 2., -4.],
          [ 3., -6.]],

         [[ 3., -2.],
          [ 6., -4.],
          [ 9., -6.]]]])
tensor([[[[0., 0.],
          [0., 0.],
          [1., 0.]],

         [[1., 0.],
          [1., 0.],
          [1., 0.]]]])
tensor([0.0000, 0.0000, 0.5000, 0.5000, 0.5000, 0.5000])
tensor(0.1667)
