In [21]:
import torch

torch.manual_seed(0)
x = torch.tensor([[1,2,3,2], [3,2,3,1]], dtype=torch.float32)
y = torch.randn(2,3,4)
x, y

(tensor([[1., 2., 3., 2.],
         [3., 2., 3., 1.]]),
 tensor([[[-1.1258, -1.1524, -0.2506, -0.4339],
          [ 0.8487,  0.6920, -0.3160, -2.1152],
          [ 0.4681, -0.1577,  1.4437,  0.2660]],
 
         [[ 0.1665,  0.8744, -0.1435, -0.1116],
          [ 0.9318,  1.2590,  2.0050,  0.0537],
          [ 0.6181, -0.4128, -0.8411, -2.3160]]]))

In [22]:
x = x.unsqueeze(1)
x

tensor([[[1., 2., 3., 2.]],

        [[3., 2., 3., 1.]]])

In [23]:
torch.einsum("tqe,tke->tqk", x,y)

tensor([[[-5.0501, -2.9457,  5.0158]],

        [[ 1.7061, 11.3822, -3.8107]]])

In [24]:
x = torch.tensor([[1,1,1,1], [2,2,2,2]], dtype=torch.float32)
x = x.T
x

tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])

In [25]:
torch.manual_seed(0)
conv_transpose = torch.nn.ConvTranspose1d(in_channels=4, out_channels=4, kernel_size=6, stride=6, bias=False)
conv_transpose.weight.T,conv_transpose.weight.T.sum(dim=-1), conv_transpose.weight.T.sum(dim=-1) * 2

(tensor([[[-0.0015, -0.0329, -0.0905,  0.0802],
          [-0.0040, -0.0796,  0.1369,  0.0188],
          [-0.1950, -0.1192,  0.0924,  0.0382],
          [-0.1384,  0.0345,  0.0078,  0.0748]],
 
         [[ 0.1095,  0.0216, -0.0074,  0.1691],
          [ 0.1618,  0.1764, -0.1202, -0.1277],
          [-0.1352,  0.1755,  0.0821, -0.0344],
          [-0.0889, -0.1906,  0.0473,  0.1032]],
 
         [[-0.1680,  0.1848,  0.1305,  0.1776],
          [-0.0181, -0.1323,  0.0380, -0.1902],
          [-0.0841,  0.0911, -0.1209, -0.0336],
          [ 0.0741, -0.1475,  0.1266,  0.1461]],
 
         [[-0.1502, -0.1894,  0.2029,  0.1801],
          [ 0.0540, -0.0940, -0.1583,  0.1814],
          [ 0.0076,  0.0989,  0.0617, -0.0934],
          [ 0.1695, -0.1052,  0.1960,  0.0763]],
 
         [[-0.0786, -0.1285,  0.0810,  0.0406],
          [-0.0617, -0.1426, -0.1415,  0.1552],
          [ 0.0807,  0.0107,  0.1121,  0.0785],
          [-0.0420,  0.1288, -0.1573, -0.2020]],
 
         [[ 0.0547, -0.05

In [26]:
conv_transpose(x)

tensor([[-0.0447,  0.2929,  0.3250,  0.0435, -0.0855, -0.1469, -0.0895,  0.5857,
          0.6500,  0.0869, -0.1710, -0.2937],
        [ 0.0720,  0.0903, -0.3026, -0.0168, -0.1906, -0.5404,  0.1441,  0.1806,
         -0.6052, -0.0337, -0.3811, -1.0807],
        [-0.1836,  0.0880, -0.1476,  0.0747,  0.2820, -0.1288, -0.3672,  0.1760,
         -0.2951,  0.1494,  0.5640, -0.2577],
        [-0.0212, -0.1290,  0.1994,  0.3366, -0.2726,  0.0652, -0.0425, -0.2579,
          0.3988,  0.6732, -0.5451,  0.1304]], grad_fn=<SqueezeBackward1>)

In [27]:
padded_X = torch.tensor([[0, 1, 1, 1, 0, 0],
                         [0, 0, 1, 1, 1, 0],
                         [0, 0, 0, 1, 1, 1]])

# Determine the shape of the padded tensor
rows, new_cols = padded_X.shape
cols = new_cols - 3  # 3 zeros were added

# Create indices for advanced indexing
start_indices = torch.arange(rows).unsqueeze(1) + torch.arange(1,cols+1).unsqueeze(0)

# Use advanced indexing to extract the original tensor
X = padded_X[torch.arange(rows).unsqueeze(1), start_indices]

print(X)


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [52]:
import torch

torch.triu(
    torch.ones(5, 7),
    diagonal=3
),

(tensor([[0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1.],
         [0., 0., 0., 0., 0., 1., 1.],
         [0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0.]]),)