In [2]:
import torch

torch.manual_seed(0)
x = torch.tensor([[1,2,3,2], [3,2,3,1]], dtype=torch.float32)
y = torch.randn(2,3,4)
x, y

(tensor([[1., 2., 3., 2.],
         [3., 2., 3., 1.]]),
 tensor([[[-1.1258, -1.1524, -0.2506, -0.4339],
          [ 0.8487,  0.6920, -0.3160, -2.1152],
          [ 0.4681, -0.1577,  1.4437,  0.2660]],
 
         [[ 0.1665,  0.8744, -0.1435, -0.1116],
          [ 0.9318,  1.2590,  2.0050,  0.0537],
          [ 0.6181, -0.4128, -0.8411, -2.3160]]]))

In [3]:
x = x.unsqueeze(1)
x

tensor([[[1., 2., 3., 2.]],

        [[3., 2., 3., 1.]]])

In [4]:
torch.einsum("tqe,tke->tqk", x,y)

tensor([[[-5.0501, -2.9457,  5.0158]],

        [[ 1.7061, 11.3822, -3.8107]]])

In [20]:
x = torch.tensor([[1,1,1], [2,2,2]], dtype=torch.float32)
x = x.T
x

tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])

In [21]:
torch.manual_seed(0)
conv_transpose = torch.nn.ConvTranspose1d(in_channels=3, out_channels=3, kernel_size=4, stride=4, bias=False)
conv_transpose.weight.T,conv_transpose.weight.T.sum(dim=-1), conv_transpose.weight.T.sum(dim=-1) * 2

(tensor([[[-0.0022, -0.2758, -0.0465],
          [-0.1112,  0.1141, -0.1817],
          [-0.0256,  0.1049, -0.1871]],
 
         [[ 0.1549, -0.1912,  0.0305],
          [ 0.0774,  0.1732, -0.0731],
          [ 0.0764,  0.2397, -0.1329]],
 
         [[-0.2376, -0.1190,  0.2614],
          [-0.0057, -0.1957, -0.1125],
          [-0.0872, -0.0594, -0.2017]],
 
         [[-0.2124,  0.0107, -0.2678],
          [ 0.2289, -0.1257,  0.2494],
          [-0.0567,  0.2160, -0.2704]]], grad_fn=<PermuteBackward0>),
 tensor([[-0.3245, -0.1788, -0.1079],
         [-0.0058,  0.1775,  0.1832],
         [-0.0952, -0.3139, -0.3483],
         [-0.4695,  0.3526, -0.1111]], grad_fn=<SumBackward1>),
 tensor([[-0.6490, -0.3576, -0.2158],
         [-0.0116,  0.3551,  0.3664],
         [-0.1904, -0.6279, -0.6967],
         [-0.9391,  0.7052, -0.2222]], grad_fn=<MulBackward0>))

In [22]:
conv_transpose(x)

tensor([[-0.3245, -0.0058, -0.0952, -0.4695, -0.6490, -0.0116, -0.1904, -0.9391],
        [-0.1788,  0.1775, -0.3139,  0.3526, -0.3576,  0.3551, -0.6279,  0.7052],
        [-0.1079,  0.1832, -0.3483, -0.1111, -0.2158,  0.3664, -0.6967, -0.2222]],
       grad_fn=<SqueezeBackward1>)

In [31]:
import torch

# Original tensor
X = torch.tensor([[1, 1, 1],
                  [1, 1, 1],
                  [1, 1, 1]])

# Determine the shape of the new tensor
rows, cols = X.shape
new_cols = cols + 3  # 3 zeros are added (1 before and 2 after)

# Create a new tensor filled with zeros
padded_X = torch.zeros((rows, new_cols), dtype=X.dtype)

# Use tensor operations to place the original values
indices = torch.arange(cols).unsqueeze(0) + torch.arange(1,rows+1).unsqueeze(1)
padded_X.scatter_(1, indices, X)

print(padded_X)


tensor([[0, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 0],
        [0, 0, 0, 1, 1, 1]])
