In [1040]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload
import os
from tsetlin import TsetlinMachine
import torch
import random

train_x = torch.tensor([[1,0],
                        [0,1],
                        [1,1],
                        [0,0]])

train_y = torch.tensor([1,1,0,0])

# seed = int.from_bytes(os.urandom(8), byteorder="big", signed=False)
# random.seed(seed)
# torch.manual_seed(seed)
# print(seed)
# random.seed(1320387042447901345)
# torch.manual_seed(1320387042447901345)
tm = TsetlinMachine(2)

for i in range(6):
    shuffled_idx = torch.randperm(train_x.shape[0])
    shuffled_x = train_x[shuffled_idx]
    shuffled_y = train_y[shuffled_idx]

    for j, (x, y) in enumerate(zip(shuffled_x, shuffled_y)):
        out_1 = tm.forward(x).item()
        tm.update(y)
        out_2 = tm.forward(x).item()
        assert y.item() == out_2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [1041]:
for x, y in zip(train_x, train_y):
    out = tm.forward(x).item()
    assert y.item() == out

In [1042]:
tm.l1.W,tm.l2.W[:, :tm.l2.W.shape[1]//2],tm.l2.W[:, tm.l2.W.shape[1]//2:]

(tensor([[18,  0,  0,  0],
         [18, 18,  0,  0],
         [ 0, 18, 18,  0],
         [ 0,  0, 18, 14],
         [18, 18,  0,  0],
         [ 0,  0,  0,  5],
         [18, 18,  0,  0],
         [18,  0,  0,  0],
         [14, 18,  0,  0],
         [ 0, 16,  0,  0]]),
 tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 tensor([[ 0, 16,  0, 12, 16,  0, 14,  0, 12,  0]]))