In [41]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload
import os
from tsetlin import TsetlinMachine
import torch
import random

DATASET_DIR = '../datasets/'
DATA_FILE = 'bit_1.txt'
SEED = "85666668775314343"

text_rows = open(f'{DATASET_DIR}{DATA_FILE}', 'r').read().splitlines()
dataset = [ [int(num) for num in row.split(',')] for row in text_rows]
tensor_dataset = torch.tensor(dataset)
train_x = tensor_dataset[:, :-1]
train_y = tensor_dataset[:, -1]

if SEED:
    random.seed(SEED)
    torch.manual_seed(SEED)
else:
    seed = int.from_bytes(os.urandom(8), byteorder="big", signed=False)
    random.seed(seed)
    torch.manual_seed(seed)
    print(seed)

tm = TsetlinMachine(train_x.shape[1], 5)

out_1 = tm.forward(train_x)
tm.update_batch(train_y)
out_2 = tm.forward(train_x)
print(out_2, train_y)
assert torch.equal(train_y,out_2)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
tensor([1, 1, 1, 1, 0, 0, 0, 0]) tensor([1, 1, 1, 1, 0, 0, 0, 0])


In [42]:
tm.l1.W, tm.l2.W, tm.l3.W

(tensor([[1, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0]]),
 tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]))

In [44]:
for _ in range(100):
    seed = int.from_bytes(os.urandom(8), byteorder="big", signed=False)
    random.seed(seed)
    torch.manual_seed(seed)
    print(seed)
    
    shuffled_idx = torch.randperm(train_x.shape[0])
    shuffled_x = train_x[shuffled_idx]
    shuffled_y = train_y[shuffled_idx]
    
    tm = TsetlinMachine(train_x.shape[1], 5)
    out_1 = tm.forward(shuffled_x)
    tm.update_batch(shuffled_y)
    out_2 = tm.forward(shuffled_x)
    assert torch.equal(shuffled_y,out_2)

14857711419414744522
343114930504402064
9070453259800326299
3137468528916550790
12049470788567563313
13645146675616886940
17331877564446867654
11933580840069109076
13164508148190493212
12309681514982378779
10043557421192628867
16420677200258418053
14754255756415110485
9023125518746001918
4266420937810541500
5497262143574501574
5709702779749144665
245571742137778858
5399228702584150666
17817781577736069532
548279252179379073
8820079468045534332
3949461085830571982
16072162192179420678
17683662279872837804
30208798429526090
12928490803762145148
5536986702221492673
5266183009037516398
18329607098371574292
2344995418645830848
17057090379297126007
12568273794029883034
11709188573345672334
4910594878574999220
17382764652346063519
10095899576796271200
13714996866522383141
8045723176345323614
2770458336914090733
18228409903503708575
12013072452240237066
5705566107532963052
15827623174187875858
5415709244188503854
2844182659894929062
2933173377704806705
14733754763096363247
10527292182349886336